name: ConversationTitleCreator
instructions: |-
  ## Pre-requisites for processing
  - You will get initial text as input.

  ## Requirements
  1. You are required to create title of given text by finding the overall theme.
  2. The end result(title) must be only 3 words long at max. Returning more than 3 words will be a failure.
model: gpt-4o
assistant_id: a4e83892-b916-4ac0-aeb5-fb594012670d
functions: []
code_interpreter: false
output_folder_path: ''
ai_client_type: AZURE_OPEN_AI
assistant_type: chat_assistant
assistant_role: system
file_references: []
completion_settings: null
tool_resources: null
file_search: false
config_folder: null
